/********************************************************************
* src/McEventCollection_p5_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/McEventCollection_p5_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMcEventCollection_p5_dict();
extern void G__cpp_setup_inheritanceMcEventCollection_p5_dict();
extern void G__cpp_setup_typetableMcEventCollection_p5_dict();
extern void G__cpp_setup_memvarMcEventCollection_p5_dict();
extern void G__cpp_setup_globalMcEventCollection_p5_dict();
extern void G__cpp_setup_memfuncMcEventCollection_p5_dict();
extern void G__cpp_setup_funcMcEventCollection_p5_dict();
extern void G__set_cpp_environmentMcEventCollection_p5_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "generator/GenParticle_p5.h"
#include "generator/GenEvent_p5.h"
#include "generator/GenVertex_p5.h"
#include "generator/McEventCollection_p5.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__McEventCollection_p5_dictLN_TClass;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_TBuffer;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_TMemberInspector;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_TObject;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlElongcOallocatorlElonggRsPgRcLcLiterator;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlElongcOallocatorlElonggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgRcLcLiterator;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLiterator;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_GenParticle_p5;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_pairlEintcOintgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_GenEvent_p5;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_GenVertex_p5;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_McEventCollection_p5;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEGenEvent_p5cOallocatorlEGenEvent_p5gRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEGenEvent_p5cOallocatorlEGenEvent_p5gRsPgRcLcLiterator;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlEGenEvent_p5cOallocatorlEGenEvent_p5gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEGenVertex_p5cOallocatorlEGenVertex_p5gRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEGenVertex_p5cOallocatorlEGenVertex_p5gRsPgRcLcLiterator;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlEGenVertex_p5cOallocatorlEGenVertex_p5gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEGenParticle_p5cOallocatorlEGenParticle_p5gRsPgR;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_vectorlEGenParticle_p5cOallocatorlEGenParticle_p5gRsPgRcLcLiterator;
extern G__linked_taginfo G__McEventCollection_p5_dictLN_reverse_iteratorlEvectorlEGenParticle_p5cOallocatorlEGenParticle_p5gRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<long,allocator<long> > G__vectorlElongcOallocatorlElonggRsPgR;
typedef vector<float,allocator<float> > G__vectorlEfloatcOallocatorlEfloatgRsPgR;
typedef vector<double,allocator<double> > G__vectorlEdoublecOallocatorlEdoublegRsPgR;
typedef vector<pair<int,int>,allocator<pair<int,int> > > G__vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR;
typedef vector<GenEvent_p5,allocator<GenEvent_p5> > G__vectorlEGenEvent_p5cOallocatorlEGenEvent_p5gRsPgR;
typedef vector<GenVertex_p5,allocator<GenVertex_p5> > G__vectorlEGenVertex_p5cOallocatorlEGenVertex_p5gRsPgR;
typedef vector<GenParticle_p5,allocator<GenParticle_p5> > G__vectorlEGenParticle_p5cOallocatorlEGenParticle_p5gRsPgR;
